export const menu = [
  {
    name: "all",
    text: "전체메뉴",
  },
  {
    name: "pasta",
    text: "파스타",
  },
  {
    name: "pizza",
    text: "피자",
  },
  {
    name: "steak",
    text: "스테이크",
  },
  {
    name: "special",
    text: "스페셜 메뉴",
  },
  {
    name: "rice",
    text: "라이스",
  },
  {
    name: "side",
    text: "사이드",
  },
  {
    name: "drink",
    text: "드링크",
  },
]

export const foodList = [
  {
    foodType: "pasta",
    name: "감바스 파스타",
    subTitle: "Gambas Pasta",
    imgUrl: "/menu/pasta/1.webp",
  },
  {
    foodType: "pasta",
    name: "감베리 파스타",
    subTitle: "Gamberi Pasta",
    imgUrl: "/menu/pasta/2.webp",
  },
  {
    foodType: "pasta",
    name: "봉골레 파스타",
    subTitle: "Vongole Pasta",
    imgUrl: "/menu/pasta/3.webp",
  },
  {
    foodType: "pasta",
    name: "알리오 올리오",
    subTitle: "Aglio e Olio",
    imgUrl: "/menu/pasta/4.webp",
  },
  {
    foodType: "pasta",
    name: "토마토 파스타",
    subTitle: "Tomato Pasta",
    imgUrl: "/menu/pasta/5.webp",
  },
  {
    foodType: "pasta",
    name: "베이컨 토마토 파스타",
    subTitle: "Bacon Tomato Pasta",
    imgUrl: "/menu/pasta/6.webp",
  },
  {
    foodType: "pasta",
    name: "땡초 베이컨 토마토 파스타",
    subTitle: "Spicy Bacon Tomato Pasta",
    imgUrl: "/menu/pasta/7.webp",
  },
  {
    foodType: "pasta",
    name: "해물 토마토 파스타",
    subTitle: "Seafood Tomato Pasta",
    imgUrl: "/menu/pasta/8.webp",
  },
  {
    foodType: "pasta",
    name: "해물 짬뽕 파스타",
    subTitle: "Seafood Jjamppong Pasta",
    imgUrl: "/menu/pasta/9.webp",
  },
  {
    foodType: "pasta",
    name: "양송이 까르보나라",
    subTitle: "Mushroom Carbonara",
    imgUrl: "/menu/pasta/10.webp",
  },
  {
    foodType: "pasta",
    name: "베이컨 까르보나라",
    subTitle: "Bacon Carbonara",
    imgUrl: "/menu/pasta/11.webp",
  },
  {
    foodType: "pasta",
    name: "매운 까르보나라",
    subTitle: "Spicy Carbonara",
    imgUrl: "/menu/pasta/12.webp",
  },
  {
    foodType: "pasta",
    name: "이태리 로제 파스타",
    subTitle: "Italian Rosé Pasta",
    imgUrl: "/menu/pasta/13.webp",
  },
  {
    foodType: "pasta",
    name: "로제 맵제 파스타",
    subTitle: "Spicy Rosé Pasta",
    imgUrl: "/menu/pasta/14.webp",
  },
  {
    foodType: "pasta",
    name: "이태리 정통 빠네",
    subTitle: "Italian Pane Cream Pasta",
    imgUrl: "/menu/pasta/15.webp",
  },
  {
    foodType: "pasta",
    name: "이태리 정통 매운 빠네",
    subTitle: "Spicy Italian Pane Cream Pasta",
    imgUrl: "/menu/pasta/16.webp",
  },
  {
    foodType: "pasta",
    name: "바질 까르보나라",
    subTitle: "Basil Carbonara",
    imgUrl: "/menu/pasta/17.webp",
  },
  {
    foodType: "pasta",
    name: "쉬림프 바질 크림 파스타",
    subTitle: "Shrimp Basil Cream Pasta",
    imgUrl: "/menu/pasta/18.webp",
  },
  {
    foodType: "pasta",
    name: "비프 바질 크림 파스타",
    subTitle: "Beef Basil Cream Pasta",
    imgUrl: "/menu/pasta/19.webp",
  },
  {
    foodType: "pizza",
    name: "미태리 치즈 피자",
    subTitle: "Mitaly Cheese Pizza",
    imgUrl: "/menu/pizza/1.webp",
  },
  {
    foodType: "pizza",
    name: "미태리 페퍼로니 피자",
    subTitle: "Mitaly Pepperoni Pizza",
    imgUrl: "/menu/pizza/2.webp",
  },
  {
    foodType: "pizza",
    name: "미태리 고르곤졸라 피자",
    subTitle: "Mitaly Gorgonzola Pizza",
    imgUrl: "/menu/pizza/3.webp",
  },
  {
    foodType: "pizza",
    name: "미태리 갈릭 포테이토 피자",
    subTitle: "Mitaly Garlic Potato Pizza",
    imgUrl: "/menu/pizza/4.webp",
  },
  {
    foodType: "steak",
    name: "시그니처 큐브 스테이크",
    subTitle: "Signature Cube Steak",
    imgUrl: "/menu/steak/1.webp",
  },
  {
    foodType: "steak",
    name: "시크릿 바베큐 폭립",
    subTitle: "Secret BBQ Pork Ribs",
    imgUrl: "/menu/steak/2.webp",
  },
  {
    foodType: "steak",
    name: "블랙페퍼 목살 스테이크",
    subTitle: "Black Pepper Pork Steak",
    imgUrl: "/menu/steak/3.webp",
  },
  {
    foodType: "special",
    name: "돈까스 필라프",
    subTitle: "Tonkatsu Pilaf",
    imgUrl: "/menu/special/1.webp",
  },
  {
    foodType: "special",
    name: "토마토 돈까스타",
    subTitle: "Tomato Tonkasta",
    imgUrl: "/menu/special/2.webp",
  },
  {
    foodType: "special",
    name: "까르보 돈까스타",
    subTitle: "Carbo Tonkasta",
    imgUrl: "/menu/special/3.webp",
  },
  {
    foodType: "special",
    name: "핫로제 돈까스타",
    subTitle: "Hot Rosé Tonkasta",
    imgUrl: "/menu/special/4.webp",
  },
  {
    foodType: "rice",
    name: "토마토 치즈 리조또",
    subTitle: "Tomato Cheese Risotto",
    imgUrl: "/menu/rice/1.webp",
  },
  {
    foodType: "rice",
    name: "크림 치즈 리조또",
    subTitle: "Cream Cheese Risotto",
    imgUrl: "/menu/rice/2.webp",
  },
  {
    foodType: "rice",
    name: "킹소시지 김치볶음밥",
    subTitle: "King Sausage Kimchi Fried Rice",
    imgUrl: "/menu/rice/3.webp",
  },
  {
    foodType: "rice",
    name: "소불고기 필라프",
    subTitle: "Beef Bulgogi Pilaf",
    imgUrl: "/menu/rice/4.webp",
  },
  {
    foodType: "rice",
    name: "스테이크 크림 리조또",
    subTitle: "Steak Cream Risotto",
    imgUrl: "/menu/rice/5.webp",
  },
  {
    foodType: "rice",
    name: "쉬림프 로제 리조또",
    subTitle: "Shrimp Rosé Risotto",
    imgUrl: "/menu/rice/6.webp",
  },
  {
    foodType: "side",
    name: "미태리 가든 샐러드",
    subTitle: "Mitaly Garden Salad",
    imgUrl: "/menu/side/1.webp",
  },
  {
    foodType: "side",
    name: "치킨텐더 샐러드",
    subTitle: "Chicken Tender Salad",
    imgUrl: "/menu/side/2.webp",
  },
  {
    foodType: "side",
    name: "오븐에 구운 바게트빵",
    subTitle: "Baked Baguette",
    imgUrl: "/menu/side/3.webp",
  },
  {
    foodType: "side",
    name: "촉촉한 수제 마늘빵",
    subTitle: "Handmade Garlic Bread",
    imgUrl: "/menu/side/4.webp",
  },
  {
    foodType: "side",
    name: "해쉬브라운",
    subTitle: "Hash Browns",
    imgUrl: "/menu/side/5.webp",
  },
  {
    foodType: "side",
    name: "감자튀김",
    subTitle: "French Fries",
    imgUrl: "/menu/side/6.webp",
  },
  {
    foodType: "side",
    name: "양념감자",
    subTitle: "Seasoned Potatoes",
    imgUrl: "/menu/side/7.webp",
  },
  {
    foodType: "side",
    name: "멘보샤",
    subTitle: "Menbosha",
    imgUrl: "/menu/side/8.webp",
  },
  {
    foodType: "side",
    name: "치킨 윙&봉",
    subTitle: "Chicken Wing and Stick",
    imgUrl: "/menu/side/9.webp",
  },
  {
    foodType: "side",
    name: "텐더스틱",
    subTitle: "Tender Stick",
    imgUrl: "/menu/side/10.webp",
  },
  {
    foodType: "drink",
    name: "자몽 에이드",
    subTitle: "Grapefruit Ade",
    imgUrl: "/menu/drink/1.webp",
  },
  {
    foodType: "drink",
    name: "레몬 에이드",
    subTitle: "Lemon Ade",
    imgUrl: "/menu/drink/2.webp",
  },
  {
    foodType: "drink",
    name: "제주 한라봉 에이드",
    subTitle: "Jeju Hallabong Ade",
    imgUrl: "/menu/drink/3.webp",
  },
  {
    foodType: "drink",
    name: "복숭아 에이드",
    subTitle: "Peach Ade",
    imgUrl: "/menu/drink/4.webp",
  },
  {
    foodType: "drink",
    name: "소다 에이드",
    subTitle: "Soda Ade",
    imgUrl: "/menu/drink/5.webp",
  },
  {
    foodType: "drink",
    name: "샹그리아 하이볼",
    subTitle: "Sangria Highball",
    imgUrl: "/menu/drink/6.webp",
  },
  {
    foodType: "drink",
    name: "샴페인 하이볼",
    subTitle: "Champagne Highball",
    imgUrl: "/menu/drink/7.webp",
  },
]
