export const regions = [
  {
    value: "seoul",
    name: "서울",
    city: [
      { value: "gangnam", name: "강남구" },
      { value: "gangdong", name: "강동구" },
      { value: "gangbuk", name: "강북구" },
      { value: "gangseo", name: "강서구" },
      { value: "gwanak", name: "관악구" },
      { value: "gwangjin", name: "광진구" },
      { value: "guro", name: "구로구" },
      { value: "geumcheon", name: "금천구" },
      { value: "nowon", name: "노원구" },
      { value: "dobong", name: "도봉구" },
      { value: "dongdaemun", name: "동대문구" },
      { value: "dongjak", name: "동작구" },
      { value: "mapo", name: "마포구" },
      { value: "seodaemun", name: "서대문구" },
      { value: "seocho", name: "서초구" },
      { value: "seongdong", name: "성동구" },
      { value: "seongbuk", name: "성북구" },
      { value: "songpa", name: "송파구" },
      { value: "yangcheon", name: "양천구" },
      { value: "yeongdeungpo", name: "영등포구" },
      { value: "yongsan", name: "용산구" },
      { value: "eunpyeong", name: "은평구" },
      { value: "jongno", name: "종로구" },
      { value: "jung", name: "중구" },
      { value: "jungnang", name: "중랑구" },
    ],
  },
  {
    value: "busan",
    name: "부산",
    city: [
      { value: "gangseo", name: "강서구" },
      { value: "geumjeong", name: "금정구" },
      { value: "nam", name: "남구" },
      { value: "dong", name: "동구" },
      { value: "dongnae", name: "동래구" },
      { value: "busanjin", name: "부산진구" },
      { value: "buk", name: "북구" },
      { value: "sasang", name: "사상구" },
      { value: "saha", name: "사하구" },
      { value: "seo", name: "서구" },
      { value: "suyeong", name: "수영구" },
      { value: "yeonje", name: "연제구" },
      { value: "yeongdo", name: "영도구" },
      { value: "jung", name: "중구" },
      { value: "haeundae", name: "해운대구" },
      { value: "gijang", name: "기장군" },
    ],
  },
  {
    value: "daegu",
    name: "대구",
    city: [
      { value: "nam", name: "남구" },
      { value: "dalseo", name: "달서구" },
      { value: "dong", name: "동구" },
      { value: "buk", name: "북구" },
      { value: "seo", name: "서구" },
      { value: "suseong", name: "수성구" },
      { value: "jung", name: "중구" },
      { value: "dalseong", name: "달성군" },
    ],
  },
  {
    value: "incheon",
    name: "인천",
    city: [
      { value: "gyeyang", name: "계양구" },
      { value: "nam", name: "남구" },
      { value: "namdong", name: "남동구" },
      { value: "dong", name: "동구" },
      { value: "bupyeong", name: "부평구" },
      { value: "seo", name: "서구" },
      { value: "yeonsu", name: "연수구" },
      { value: "jung", name: "중구" },
      { value: "ganghwa", name: "강화군" },
      { value: "ongjin", name: "옹진군" },
    ],
  },
  {
    value: "gwangju",
    name: "광주",
    city: [
      { value: "gwangsan", name: "광산구" },
      { value: "nam", name: "남구" },
      { value: "dong", name: "동구" },
      { value: "buk", name: "북구" },
      { value: "seo", name: "서구" },
    ],
  },
  {
    value: "daejeon",
    name: "대전",
    city: [
      { value: "daedeok", name: "대덕구" },
      { value: "dong", name: "동구" },
      { value: "seo", name: "서구" },
      { value: "yuseong", name: "유성구" },
      { value: "jung", name: "중구" },
    ],
  },
  {
    value: "ulsan",
    name: "울산",
    city: [
      { value: "nam", name: "남구" },
      { value: "dong", name: "동구" },
      { value: "buk", name: "북구" },
      { value: "jung", name: "중구" },
      { value: "ulju", name: "울주군" },
    ],
  },
  {
    value: "gangwon",
    name: "강원",
    city: [
      { value: "gangneung", name: "강릉시" },
      { value: "donghae", name: "동해시" },
      { value: "samcheok", name: "삼척시" },
      { value: "sokcho", name: "속초시" },
      { value: "wonju", name: "원주시" },
      { value: "chuncheon", name: "춘천시" },
      { value: "taebaek", name: "태백시" },
      { value: "goseong", name: "고성군" },
      { value: "yanggu", name: "양구군" },
      { value: "yangyang", name: "양양군" },
      { value: "yeongwol", name: "영월군" },
      { value: "inje", name: "인제군" },
      { value: "jeongseon", name: "정선군" },
      { value: "cheorwon", name: "철원군" },
      { value: "pyeongchang", name: "평창군" },
      { value: "hongcheon", name: "홍천군" },
      { value: "hwacheon", name: "화천군" },
      { value: "hoengseong", name: "횡성군" },
    ],
  },
  {
    value: "gyeonggi",
    name: "경기",
    city: [
      { value: "goyang", name: "고양시" },
      { value: "gwacheon", name: "과천시" },
      { value: "gwangmyeong", name: "광명시" },
      { value: "gwangju", name: "광주시" },
      { value: "guri", name: "구리시" },
      { value: "gunpo", name: "군포시" },
      { value: "gimpo", name: "김포시" },
      { value: "namyangju", name: "남양주시" },
      { value: "dongducheon", name: "동두천시" },
      { value: "bucheon", name: "부천시" },
      { value: "seongnam", name: "성남시" },
      { value: "suwon", name: "수원시" },
      { value: "siheung", name: "시흥시" },
      { value: "ansan", name: "안산시" },
      { value: "anseong", name: "안성시" },
      { value: "anyang", name: "안양시" },
      { value: "osan", name: "오산시" },
      { value: "yongin", name: "용인시" },
      { value: "uiwang", name: "의왕시" },
      { value: "uijeongbu", name: "의정부시" },
      { value: "icheon", name: "이천시" },
      { value: "paju", name: "파주시" },
      { value: "pyeongtaek", name: "평택시" },
      { value: "hanam", name: "하남시" },
      { value: "hwaseong", name: "화성시" },
      { value: "gapyeong", name: "가평군" },
      { value: "yangju", name: "양주군" },
      { value: "yangpyeong", name: "양평군" },
      { value: "yeoju", name: "여주군" },
      { value: "yeoncheon", name: "연천군" },
      { value: "pocheon", name: "포천군" },
    ],
  },
  {
    value: "gyeongnam",
    name: "경남",
    city: [
      { value: "geoje", name: "거제시" },
      { value: "gimhae", name: "김해시" },
      { value: "masan", name: "마산시" },
      { value: "miryang", name: "밀양시" },
      { value: "sacheon", name: "사천시" },
      { value: "yangsan", name: "양산시" },
      { value: "jinju", name: "진주시" },
      { value: "jinhae", name: "진해시" },
      { value: "changwon", name: "창원시" },
      { value: "tongyeong", name: "통영시" },
      { value: "geochang", name: "거창군" },
      { value: "goseong", name: "고성군" },
      { value: "namhae", name: "남해군" },
      { value: "sancheong", name: "산청군" },
      { value: "uiryeong", name: "의령군" },
      { value: "changnyeong", name: "창녕군" },
      { value: "hadong", name: "하동군" },
      { value: "haman", name: "함안군" },
      { value: "hamyang", name: "함양군" },
      { value: "hapcheon", name: "합천군" },
    ],
  },
  {
    value: "gyeongbuk",
    name: "경북",
    city: [
      { value: "gyeongsan", name: "경산시" },
      { value: "gyeongju", name: "경주시" },
      { value: "gumi", name: "구미시" },
      { value: "gimcheon", name: "김천시" },
      { value: "mungyeong", name: "문경시" },
      { value: "sangju", name: "상주시" },
      { value: "andong", name: "안동시" },
      { value: "yeongju", name: "영주시" },
      { value: "yeongcheon", name: "영천시" },
      { value: "pohang", name: "포항시" },
      { value: "goryeong", name: "고령군" },
      { value: "gunwi", name: "군위군" },
      { value: "bonghwa", name: "봉화군" },
      { value: "seongju", name: "성주군" },
      { value: "yeongdeok", name: "영덕군" },
      { value: "yeongyang", name: "영양군" },
      { value: "yecheon", name: "예천군" },
      { value: "ulleung", name: "울릉군" },
      { value: "uljin", name: "울진군" },
      { value: "uiseong", name: "의성군" },
      { value: "cheongdo", name: "청도군" },
      { value: "cheongsong", name: "청송군" },
      { value: "chilgok", name: "칠곡군" },
    ],
  },
  {
    value: "jeonnam",
    name: "전남",
    city: [
      { value: "gwangyang", name: "광양시" },
      { value: "naju", name: "나주시" },
      { value: "mokpo", name: "목포시" },
      { value: "suncheon", name: "순천시" },
      { value: "yeosu", name: "여수시" },
      { value: "gangjin", name: "강진군" },
      { value: "goheung", name: "고흥군" },
      { value: "gokseong", name: "곡성군" },
      { value: "gurye", name: "구례군" },
      { value: "damyang", name: "담양군" },
      { value: "muan", name: "무안군" },
      { value: "boseong", name: "보성군" },
      { value: "sinan", name: "신안군" },
      { value: "yeonggwang", name: "영광군" },
      { value: "yeongam", name: "영암군" },
      { value: "wando", name: "완도군" },
      { value: "jangseong", name: "장성군" },
      { value: "jangheung", name: "장흥군" },
      { value: "jindo", name: "진도군" },
      { value: "hampyeong", name: "함평군" },
      { value: "haenam", name: "해남군" },
      { value: "hwaseong", name: "화순군" },
    ],
  },
  {
    value: "jeonbuk",
    name: "전북",
    city: [
      { value: "gunsan", name: "군산시" },
      { value: "gimje", name: "김제시" },
      { value: "namwon", name: "남원시" },
      { value: "iksan", name: "익산시" },
      { value: "jeonju", name: "전주시" },
      { value: "jeongeup", name: "정읍시" },
      { value: "gochang", name: "고창군" },
      { value: "muju", name: "무주군" },
      { value: "buan", name: "부안군" },
      { value: "sunchang", name: "순창군" },
      { value: "wanju", name: "완주군" },
      { value: "imsil", name: "임실군" },
      { value: "jangsu", name: "장수군" },
      { value: "jinan", name: "진안군" },
    ],
  },
  {
    value: "jeju",
    name: "제주",
    city: [
      { value: "seogwipo", name: "서귀포시" },
      { value: "jeju", name: "제주시" },
      { value: "namjeju", name: "남제주군" },
      { value: "bukjeju", name: "북제주군" },
    ],
  },
  {
    value: "chungnam",
    name: "충남",
    city: [
      { value: "asan", name: "아산시" },
      { value: "boryeong", name: "보령시" },
      { value: "cheonan", name: "천안시" },
      { value: "gongju", name: "공주시" },
      { value: "nonsan", name: "논산시" },
      { value: "seosan", name: "서산시" },
      { value: "dangjin", name: "당진군" },
      { value: "geumsan", name: "금산군" },
      { value: "buyeo", name: "부여군" },
      { value: "seocheon", name: "서천군" },
      { value: "cheongyang", name: "청양군" },
      { value: "taean", name: "태안군" },
      { value: "hongseong", name: "홍성군" },
      { value: "yesan", name: "예산군" },
    ],
  },
  {
    value: "chungbuk",
    name: "충북",
    city: [
      { value: "cheongju", name: "청주시" },
      { value: "cheongwon", name: "청원군" },
      { value: "jecheon", name: "제천시" },
      { value: "chungju", name: "충주시" },
      { value: "boeun", name: "보은군" },
      { value: "danyang", name: "단양군" },
      { value: "goesan", name: "괴산군" },
      { value: "eumseong", name: "음성군" },
      { value: "okcheon", name: "옥천군" },
      { value: "jeungpyeong", name: "증평군" },
      { value: "jincheon", name: "진천군" },
      { value: "yeongdong", name: "영동군" },
    ],
  },
]
